### PR TITLE
Change parameter expr_form to tgt_type

### PR DESCRIPTION
**Pull request by ghost**
https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html#expr-form-deprecation
```
DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.
```

### CODE REVIEW

**Comment by ghost** [comment]
@gtmanfred @mattp- can you review, please?

**Comment by mattp-** [comment]
@ViktorPegy seems generally reasonable. I'm not actively maintaining this at the moment but given the straightforwardness of the change it should be fine. if the failures are not relevant to your changes I can merge and release.

**Comment by ghost** [comment]
@mattp- yes, the failures are not relevant to my changes

**Comment by ghost** [comment]
@mattp- can u merge the request and make the release?

**Comment by mattp-** [comment]
@ViktorPegy actually, seems like salt removed me as a maintainer on this repo, so can't do anything for you. sorry!

**Pull request closed without merging**
