### PR TITLE
Add ability to run runners to pepper

### PR DESCRIPTION
**Pull request by jalons**
We use this locally to check manage.status remotely

### CODE REVIEW

**Comment by jalons** [comment]
I've also tried the following:

```
      def lookup_jid(self, jid):
          '''
          Get job results

          Wraps :meth:`runner`.
          '''
          return self.runner(fun='jobs.lookup_jid', kwargs={'jid': jid})


      def runner(self, fun, kwargs=None):
          '''
          Run a single command using the ``runner`` client
          Wraps :meth:`low`.
          '''
          low = {
              'client': 'runner',
              'fun': fun,
          }

          if kwargs:
              assert type(kwargs) == dict
              low.update(kwargs)

          return self.low([low], path='/')
```

To reduce the duplicate runner, but I don't think kwargs needing to be a dict is technically accurate.  Thoughts?

**Comment by whiteinge** [comment]
Great addition.

What version of Salt are you testing on? I think the `arg` and `kwarg` was a recent accidental addition (2015.5). We may indeed keep it though.

For use with previous Salt versions though the latter form from your comment is necessary. `kwargs` must be a dict. You could enforce that and provide a nice function interface similar to the actual RunnerClient, e.g.:

```python
 def runner(self, fun, **kwargs):
          '''
          Run a single command using the ``runner`` client

          Usage::

            runner('jobs.lookup_jid', jid=12345)
          '''
          low = {
              'client': 'runner',
              'fun': fun,
          }

          low.update(kwargs)

          return self.low([low], path='/')
```

**Comment by whiteinge** [comment]
Indeed we are keeping args/kwargs: saltstack/salt##25243

**Comment by jalons** [comment]
Sorry, didn't fast forward that commit.  To reduce noise, I'll close this one, fix it up, (actually test, no local install of salt currently at home), and resubmit.

**Comment by jalons** [comment]
With the above suggested ```**kwargs``` I get the following:
```
low: {'fun': 'jobs.lookup_jid', 'client': 'runner', 'kwargs': {'jid': u'20150708194856769812'}}
```

To work with my current version of salt (```0.17.5```) the working low is:
```
low: {'fun': 'jobs.lookup_jid', 'jid': u'20150708194856769812', 'client': 'runner'}
```

Suggestions on how to proceed?  We're in the process of upgrading to 2015.5 currently, but I have not set up salt-api yet in that environment to test this against. I can do that tomorrow.

**Comment by whiteinge** [comment]
Your second example is correct.

Do you see where in the code the `**kwargs` dict is getting shoved into `low['kwargs']`? That doesn't sound right. :(

**Comment by jalons** [comment]
I was passing kwargs in as a dictionary, silly me. I rebased down to a single commit, as well.

**Comment by whiteinge** [comment]
Hawt! Thank you, sir.

**Comment by jalons** [comment]
Fantastic.  How often do you push new versions to pypi? Just need to know if I should wait or just package myself (for local mirroring).

**Comment by whiteinge** [comment]
Ask and ye shall receive, friend @jalons! ...with the notable exception that PyPI is throwing a 500 when I try to push the release. I'll try again shortly. If you only care about the sdist it is available on the release page:

https://github.com/saltstack/pepper/releases/tag/0.3.6

**Comment by whiteinge** [comment]
Went through on PyPI.

**Comment by jalons** [comment]
Thanks @whiteinge!

**Pull request merged**
