### PR TITLE
Support salt-api URL that contains paths

### PR DESCRIPTION
**Pull request by alf**
This patch makes it possible to use a SALTAPI_URL that contains a path in addition to the protocol and host. For example "https://example.com/salt-api/".

The problem is the use of `urljoin(base, url)`. `url` can be absolute or relative. If it is absolute (as was the case in pepper) the path of `base` will be dropped.

```python
>>> urlparse.urljoin("http://example.com/salt-api/", "/")
'http://example.com/'
>>> urlparse.urljoin("http://example.com/salt-api/", "")
'http://example.com/salt-api/'
```

### CODE REVIEW

**Comment by whiteinge** [comment]
This is a great addition! Thanks for sending it in.  :+1: 

Rather than modify the path of each endpoint, I would prefer to see this implemented as a new setting, `root_prefix` (to match the salt-api setting of the same name). That could then be urljoin'ed between `api_url` and `path` [here](https://github.com/alf/pepper/blob/7e53a6e/pepper/libpepper.py#L98).

Would you mind reworking your pull request like that?

**Comment by alf** [comment]
I don't mind changing the fix. 

I hope you don't mind me suggesting that we parse the original SALTAPI_URL setting to extract the path instead of adding another option. As a user I expect that a URL can contain paths.

**Comment by whiteinge** [comment]
That works. :)

**Comment by alf** [comment]
My second attempt to get this accepted adds a _construct_url method. The reason I did it this way is that it felt silly to extract the path from SALTAPI_URL just to add it back in a moment later.

I also moved the validation of SALTAPI_URL to the constructor. I believe that both the requests and the urllib implementation of `req` should have this logic. Further, it seems better that the exception is raised when we instantiate the api and not when we try to use it.

This might be considered a different change, so I can split it out into a different pull request if you prefer.

**Comment by whiteinge** [comment]
Cool. Thanks for making that change and thanks for the contribution!

**Pull request merged**
